### PR TITLE
yii.activeForm.js not getting registered on empty tree

### PR DESCRIPTION
**Pull request by Konrad90**
js error was thrown when adding root node to empty tree because yii.activeForm.js was not getting registered in that case

### CODE REVIEW

**Comment by kartik-v** [comment]
Check with the latest code from dev-master... this may not be needed.

**Comment by Konrad90** [comment]
Updated my sources but still getting the error thrown when hitting Add new root on an empty tree. The loading animation keeps spinning. But the form and everything still works. Just a visual bug.

error234235

**Comment by kartik-v** [comment]
Upgrade to latest - this fix is not needed. The dependencies have been set via asset bundles.

**Comment by Konrad90** [comment]
Yes, it works great now. Thanks.

**Pull request closed without merging**
